/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Demo: typeof import('./src/components/SplashScreen/demo.vue')['default']
    LyricScroller: typeof import('./src/components/LyricScroller/index.vue')['default']
    MiniPlayer: typeof import('./src/components/MiniPlayer/index.vue')['default']
    PlaylistPanel: typeof import('./src/components/PlaylistPanel/index.vue')['default']
    SplashScreen: typeof import('./src/components/SplashScreen/index.vue')['default']
  }
}
